version: 0.2

env:
  git-credential-helper: yes
  variables:
    TF_VERSION: "1.0.11"
    TERRAFORM_WORKSPACE: dev
  #parameter-store:
    #maybe_password: "/secret-params/test/some/password"

phases:
  install:
    commands:
      - echo "Installing terraform via tfenv. Make sure you have .terraform-version set in your repository"
      - git clone https://github.com/tfutils/tfenv.git ~/.tfenv
      - 'ln -s ~/.tfenv/bin/* /usr/local/bin/'
      - tfenv install
  pre_build:
    commands:
      - if ! terraform workspace list | grep $TERRAFORM_WORKSPACE; then terraform workspace new $TERRAFORM_WORKSPACE; fi
      - terraform workspace select $TERRAFORM_WORKSPACE
      - terraform init
      - terraform validate
  build:
    commands:
      - terraform apply -no-color -auto-approve
